include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - prefer_const_constructors
    - prefer_single_quotes
    - curly_braces_in_flow_control_structures
    - always_specify_types
    - avoid_print
    - no_duplicate_case_values
    - unawaited_futures
    - unnecessary_parenthesis