name: pda3
description: A new Flutter project.

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3

  # Routing
  go_router: ^12.1.1

  # Networking
  dio: ^5.4.0

  # Environment Variables
  flutter_dotenv: ^5.1.0

  # Code Generation Helpers
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0

  # Internationalization
  intl: ^0.19.0

  # Local Storage
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

  # Code Generators
  build_runner: ^2.4.7
  riverpod_generator: ^2.3.9
  freezed: ^2.4.6
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - .env.dev
    - .env.prod